apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-xufmgwij
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-xufmgwij:69895b7580a64c4c50c06c7acec3b4503e83fa92@sha256:8e53a8f50fd21cdbc877ec1e58580e86ca5743e5769cb641047abb352b119d2b
        name: container-image  
